# Generated by Django 5.2.8 on 2025-11-19 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('poster_link', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.CharField(blank=True, max_length=255, null=True)),
                ('certif', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_score', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('star_one', models.CharField(blank=True, max_length=255, null=True)),
                ('star_two', models.CharField(blank=True, max_length=255, null=True)),
                ('star_three', models.CharField(blank=True, max_length=255, null=True)),
                ('star_four', models.CharField(blank=True, max_length=255, null=True)),
                ('num_votes', models.CharField(blank=True, max_length=255, null=True)),
                ('gross', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
